general:
  hostname: caffo-reader.herokuapp.com
  username: caffo
  password: caffocaffo21

superfeedr:
  username: zenburn
  password: arcana333

feeds:
  - http://www.flickr.com/photos/factoryjoe/
  - http://chneukirchen.org/trivium/index.atom
  - http://feeds.feedburner.com/ToboldsBlog
  - http://tinysubversions.com/feed/
  - http://usesthis.com/feed/
  - http://tagn.wordpress.com/feed/
  - http://tabletitans.com/feed
  - http://www.rockpapershotgun.com/feed/
  - http://www.rockpapershotgun.com/feed/
  - http://www.postsecret.com/feeds/posts/default?alt=rss
  - http://randomshopper.tumblr.com/rss
  - http://pessoal.zehfernando.com/feed/
  - http://onethingwell.org/rss
  - http://objetosdedesejo.com/feed/
  - http://www.marco.org/rss
  - http://minimalmac.com/rss
  - http://gostosa.tumblr.com/rss
  - http://blog.instapaper.com/rss
  - http://dragonchasers.com/feed/
  - http://daringfireball.net/index.xml
  - http://feeds.feedburner.com/blogdoiphone/posts/
  - http://beautifulpixels.com/feed/
  - http://feeds.feedburner.com/AppSites